export {default as FormInput} from './FormInput'
export {default as SubmitBtn} from './SubmitBtn'
export {default as Hero} from './Hero'
export {default as SectionTitle} from './SectionTitle'
export {default as FeaturedProducts} from './FeaturedProducts'
export {default as Filters} from './Filters'
export {default as PaginationConatiner } from './PaginationContainer'
export {default as ProductsContainer } from './ProductsContainer'
export {default as CartItemsList } from './CartItemsList'
export {default as CartTotals } from './CartTotals'

